import NavBar from "@/components/navBar/navBar";
import "./globals.css";
import type { Metadata } from "next";
import { ReactNode } from "react";
import { Inter } from "next/font/google";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

type RootLayoutTypes = Readonly<{ children: ReactNode }>;

const RootLayout = ({ children }: RootLayoutTypes) => {
  return (
    <html lang="en">
      <body suppressHydrationWarning className={inter.className}>
        <div className={"secondBody"}>
          <NavBar />
          {children}
        </div>
      </body>
    </html>
  );
};
export default RootLayout;
